### PR TITLE
Remove loops and use assembly instead

### PR DESCRIPTION
**Pull request by i-stam**
Just the same old assembly: the last function  is from dear Nick so more or less my approach must be ok. 

I made it more explicit by using `uint startByte = _from + 32; //first 32 bytes denote the array length`
instead of the more hackery `x := mload(add(_bts, add(0x20, _from)))`.

please choose what feels better. I didn't change the last one because we state the source of the code explicitly in the comments.

### CODE REVIEW

**Comment by i-stam** [comment]
By the way I am not sure if this has been audited by ToB...the executeCall() was for sure
`function _executeCall(address _to, uint256 _value, bytes memory _data) internal returns (bool) {
        bool success;
        // solium-disable-next-line security/no-inline-assembly
        assembly {
            success := call(gas, _to, _value, add(_data, 0x20), mload(_data), 0, 0)
        }
        return success;
    }`

**Comment by mischat** [comment]
Do we need anymore tests here or are you happy with this now @i-stam ?

**Comment by mischat** [comment]
if and when you are happy I will go through your tests, and based on the unit tests I see I will accept as I don't really understand assumbly :)

**Comment by i-stam** [comment]
I think that the test cover all the "edge" cases and some random ones. You don't really need to understand what the code does, take is a black box: e.g. i feed it with bytes I get an address, so if you think there is something missing, feel free to update the test, otherwise you can merge it i guess.

**Pull request merged**
