### PR TITLE
Update version declaration in go.mod

### PR DESCRIPTION
**Pull request by novemberborn**

### CODE REVIEW

**Comment by tav** [comment]
My main concern once we fork into `/v2` is that it becomes extremely painful to make changes to multiple versions. If we're going ahead with this approach, that's fine but then someone needs to own it, because otherwise it's going to become code that few people would want to touch.

**Comment by mischat** [comment]
I have looked at this, I am indifferent. I don't think this gets in the way of people writing and testing solidity in any shape or form.

**Comment by mischat** [comment]
feel free to merge

**Comment by mischat** [comment]
We should have a longer conversation about synk.

**Pull request merged**
