### PR TITLE
Echidna tests

### PR DESCRIPTION
**Pull request by nostdm**
- Fixed/modified existing Echidna tests cases
- Updated README.md
- Created new Echidna test cases
- Deleted outdated test cases (e.g. stringProps)
- Added new configuration options (e.g. timeout)
- Parallelized all CircleCI tests

### CODE REVIEW

**Comment by mischat** [comment]
I guess we need to make it so that it doesn't fail the build :)

**Comment by mischat** [comment]
I saw the output, I need to look at the tests.

**Comment by nostdm** [comment]
I forgot to push the latest changes, the tests should be passing now.

**Comment by nostdm** [comment]
Once we merge the other PRs I will rebase this from master

**Comment by mischat** [comment]
👍

**Comment by nostdm** [comment]
Going to recreate this PR to see if the CircleCI checks show up properly.

**Pull request closed without merging**
