### PR TITLE
Add balance check for gas top up

### PR DESCRIPTION
**Pull request by riccardopersiani**

### CODE REVIEW

**Review by nostdm — APPROVED** [review]
Looks good. I fixed the slither CI job and left some comments about the tests.

**Comment by riccardopersiani** [comment]
@nostdm re the slither, this PR is supposed to be merged after the Remove Oraclize PR, where all the tools are updated and the CI is passing correctly.

**Comment by nostdm** [comment]
@riccardopersiani Ah, IMO the branch should be branched off from the branch in question so that it's obvious that the PRs are related - you can always rebase from master after - otherwise it's hard to review a failing PR. Also would be nice to have some PR comments about the changes implemented and the reasoning behind them.

**Review by mischat — COMMENTED** [review]
This looks great to me. Thanks

**Pull request merged**
